CREATE TABLE TRIP26.MEMBER
(
  MEMBER_ID      VARCHAR2(50 BYTE) CONSTRAINT member_id_pk PRIMARY KEY,
  EMAIL          VARCHAR2(255 BYTE)             NOT NULL,
  PASSWORD       VARCHAR2(255 BYTE)             NOT NULL,
  NAME           VARCHAR2(50 BYTE)              NOT NULL,
  NICKNAME       VARCHAR2(50 BYTE)              NOT NULL,
  PROFILE_IMAGE  VARCHAR2(4000 BYTE),
  SOCIAL_TYPE    VARCHAR2(20 BYTE),
  ROLE           VARCHAR2(20 BYTE)              NOT NULL,
  ACCESS_TOKEN   VARCHAR2(100 BYTE),
  REFRESH_TOKEN  VARCHAR2(100 BYTE),
  CREATE_DATE    VARCHAR2(50 BYTE),
  LATEST_DATE    VARCHAR2(50 BYTE),
  STATUS         VARCHAR2(20 BYTE)              NOT NULL
);
